name: Build Project

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'logbog/**'
      - 'uml/**'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      width:
        name: jar-files
        path: staging