name: Build Project

on:
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'logbog/**'
      - 'uml/**'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build with Maven
      run: |
        mvn -B package --file pom.xml
        mkdir staging && cp target/*.jar staging

    - name: Make Directories
      run: |
        mkdir libs
        mkdir libs/win
        mkdir libs/mac

    - name: Download OpenJDK 15
      run: |
        wget -O libs/win https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_windows-x64_bin.zip
        wget -O libs/mac https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_osx-x64_bin.tar.gz

    - name: Extract ZIP
      uses: TonyBogdanov/zip@1.0
      with:
          args: unzip -qq libs/win/openjdk-15.0.0.1_windows-x64_bin.zip -d libs/win
      
    - name: Extract Tarball for Mac
      run: tar -czvf libs/mac/openjdk-15.0.1_osx-x64_bin.tar.gz libs/mac

    - name: Copy JDKs into staging
      run: cp -vr libs staging

    - name: Copy Static into Staging
      run: cp -vr static staging

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: jar-files
        path: staging